# generated by Git for Windows
#test -f ~/.profile && . ~/.profile
#test -f ~/.bashrc && . ~/.bashrc

# Load .bashrc if available
if [ -f ~/.bashrc ]; then
    source ~/.bashrc
	source ~/.dotfiles/.bash_prompt
fi

# Set PATHS
if [ -x "/C/Program Files/Git/bin/git.exe" ]; then
    # Adjust the path as needed to point to your Git installation directory
    export PATH="/C/Program Files/Git/bin:$PATH"
fi

